#!/bin/bash
cd "${0%/*}"

DISPLAY=:0 jre/bin/java -Xmx700m --module-path . --add-modules ALL-MODULE-PATH -Djavafx.platform=gtk -Djavafx.verbose=true -Dprism.verbose=true -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.virtualKeyboard=javafx com.stream_pi.client.Main -DStreamPi.showShutDownButton=true -DStreamPi.startupRunnerFileName=run_desktop -DStreamPi.isXMode=true
